source 'git@github.com:shapehq/ShapePodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


platform :ios, '6.0'
pod 'ReactiveCocoa', '2.0'

post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) USE_REACTIVE_EXTENSION=1'
    end
  end
end
