source 'https://github.com/CocoaPods/Specs.git'
source 'git@bitbucket.org:shapedk/shapepodspecs.git'
source 'git@github.com:shapehq/ShapePodSpecs.git'

platform :ios, '8.0'
inhibit_all_warnings!

pod 'SHPFoundation', '~> 2.3.2'
pod 'SHPUIKit', '~> 2.1.0'
pod 'SHPSideMenu', '~> 1.1.0'
pod 'DCIntrospect-ARC', :head, :configurations => ['Debug']
pod 'Masonry', '~> 0.6.1'
pod 'ReactiveCocoa', '~> 2.4.7'
pod 'SHPNetworking'#, '~> 7.6.0'
pod 'SHPCalendarPicker', :git => 'git@github.com:miklselsoe/SHPCalendarPicker.git'
pod 'SHPRACAdditions', '~> 0.1.2'
#pod 'SHPCalendarPicker', :path => '~/Development/SHPCalendarPicker'

# pod 'dyci', :git => 'https://github.com/DyCI/dyci-main.git'


# Will inject pod license acknowledgements into Settings bundle
post_install do | installer |
    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods/Pods-Acknowledgements.plist', 'Resources/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
    
    installer.project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) USE_REACTIVE_EXTENSION=1'
        end
    end
end

