source 'https://github.com/CocoaPods/Specs.git'
source 'git@bitbucket.org:shapedk/shapepodspecs.git'
source 'git@github.com:shapehq/ShapePodSpecs.git'

platform :ios, '8.0'
inhibit_all_warnings!

pod 'SHPFoundation', '~> 2.3.2'
pod 'SHPPrototypeKit', '~> 0.5.1'

# pod 'DCIntrospect-ARC'
# pod 'dyci', :git => 'https://github.com/DyCI/dyci-main.git'


# Will inject pod license acknowledgements into Settings bundle
post_install do | installer |
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods/Pods-Acknowledgements.plist', 'Resources/Settings.bundle/Acknowledgements.plist', :remove_destination => true)

# in-comment this if you want to use the Reactive Extensions to SHPNetworking
  # installer.project.targets.each do |target|
  #   target.build_configurations.each do |config|
  #     config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) USE_REACTIVE_EXTENSION=1'
  #   end
  # end
end
