#define NSLog(s,...)

#define CHDInvitationNoAnswer @"no-answer"
#define CHDInvitationAccept @"yes"
#define CHDInvitationMaybe @"maybe"
#define CHDInvitationDecline @"no"

#define keventsTimestamp @"eventsTimestamp"
#define kcalendarTimestamp @"calendarTimestamp"
#define kSavedEventBool @"savedEventBool"
#define kinvitationsTimestamp @"invitationsTimestamp"
#define kmessagesTimestamp @"messagesTimestamp"
#define knewMessageBool @"newMessageBool"
#define kpeopleTimestamp @"peopleTimestamp"
#define ksuccessfulPeopleMessage @"successfulPeopleMessage"
#define ktoPeopleClicked @"toPeopleClicked"
#define kpersonSuccessfullyAdded @"personSuccessfullyAdded"
#define kPeopleMessageText @"peopleMessageText"
#define kPeopleSMSText @"peopleSMSText"
#define kpeopleSubjectText @"peopleSubjectText"
#define kselectedPeopleArray @"selectedPeopleArray"
#define kcurrentuser @"currentUser"
#define kselectedOrganizationIdforPeople @"selectedOrganizationIdForPeople"
#define khideTabButtons @"hideTabButtons"

#define kEvent @"event"
#define kAbsence @"absence"
#define kpeopleImage @"peopleImage"
#define kloginwithTouchIdDisabled @"loginWithTouchIdDisabled"
#define kuserEmail @"userEmail"
#define kuserPassword @"userPassword"
